create database netflixmovies;
use netflixmovies;
select * from netflix_movies_and_tv_shows;
desc netflix_movies_and_tv_shows;
Select count(*) from netflix_movies_and_tv_shows;
select distinct type from netflix_movies_and_tv_shows;
select * from netflix_movies_and_tv_shows limit 10;
select * from netflix_movies_and_tv_shows where type='Movie' and 'release_year'=2020;
select * from netflix_movies_and_tv_shows where type='TV Show' and  country = 'India';
select * from netflix_movies_and_tv_shows where title like '%Love%';
select * from netflix_movies_and_tv_shows order by 'release_year' desc limit 5;
select * from netflix_movies_and_tv_shows where type = 'Movie' and duration like '%min%' order by cast(SUBSTRING_INDEX(duration, ' ', 1) AS UNSIGNED) desc limit 10;
select type, count(*)  as total from netflix_movies_and_tv_shows group by type;
select title,count(*) as total from netflix_movies_and_tv_shows where title is not null group by title order by total desc limit 10;
select 'release_year', COUNT(*) AS total from netflix_movies_and_tv_shows group by 'release_year' order by 'release_year';
select country, COUNT(*) as total from netflix_movies_and_tv_shows  where country is not null group by country order by total desc limit 10;
select * FROM netflix_movies_and_tv_shows where title is null or title = '';
select COUNT(*) from netflix_movies_and_tv_shows WHERE country is null or country = '';
select * from netflix_movies_and_tv_shows where rating in ('G', 'TV-Y');
select * from netflix_movies_and_tv_shows WHERE type = 'TV Show' and country = 'United States' and  'release_year' > 2015;
select * from netflix_movies_and_tv_shows WHERE genre is not null and genre like '%a';
select * from netflix_movies_and_tv_shows where YEAR(STR_TO_DATE('release_year', '%M %d, %Y')) = 2021;
select * from netflix_movies_and_tv_shows ORDER BY 'ReleaseYear' asc limit 5;
